version: '3'

services:
  mysql:
    image: mysql:8
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - '33306:3306'
    tmpfs: /var/lib/mysql8
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

